source ~/.vim/rc.d/0.pkgs.vim

source ~/.vim/rc.d/1.theme.vim
source ~/.vim/rc.d/1.custom.vim
source ~/.vim/rc.d/1.syntax.vim

source ~/.vim/rc.d/2.snippets.vim

source ~/.vim/rc.d/2.bubbling.vim
source ~/.vim/rc.d/2.persistundo.vim
source ~/.vim/rc.d/2.emacscmdl.vim
source ~/.vim/rc.d/3.venv.vim

source ~/.vim/rc.d/z.leader.vim

" TODO consider fresh https://github.com/freshshell/fresh
" TODO consider search https://github.com/jasoncodes/dotfiles/blob/master/vim/config/search.vim
