# sourced after .zshrc for a login shell
source "$DOTFILES/bash-like-common/profile"
# # OS X 10.8 defines a /etc/zprofile that is exactly the same as /etc/zshenv.
# # This has the wonderful effect of resetting the paths.
# setup_paths
