
# loaded by bash from login shells
# shellcheck source=/dev/null
. "$HOME/.bashrc"

source_file_if_exists "$HOME/.dotfiles/bash-like-common/profile"
source_file_if_exists "$HOME/.dotfiles_local/bash_profile"
